sudo: required
services:
  - docker
language: python
python:
  - "2.7"
env:
  matrix:
    - IMAGE=jessie
script:
    - ./run-tests.py test $IMAGE -v
    - ./run-tests.py dev $IMAGE --salt --postgres --cmd "salt-call -l debug --hard-crash --retcode-passthrough state.sls patchwork.dbsetup"
    - ./run-tests.py dev $IMAGE --salt --cmd "salt-call -l debug --hard-crash --retcode-passthrough state.sls patchwork.gunicorn"
